language: shell
sudo: false


install:
  # Install lastest nvm
  - rm -rf ~/.nvm 
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install 11

  # Install nightly rust
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - sh /tmp/rustup.sh --default-toolchain nightly -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - source "$HOME/.cargo/env"

  # Install other dependencies
  - npm install --ignore-scripts

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  npm: true
  directories:
    - /home/travis/.cargo
# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

branches:	
  except:	
  - master

script:
  # 11
  - neon build --release
  - mv native/index.node $SWC_NAME-67.node
  # 10
  - nvm install 10
  - neon build --release
  - mv native/index.node $SWC_NAME-64.node
  # 8
  - nvm install 8
  - neon build --release
  - mv native/index.node $SWC_NAME-57.node
  # 6
  - nvm install 6
  - neon build --release
  - mv native/index.node $SWC_NAME-48.node

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    - $SWC_NAME-48.node
    - $SWC_NAME-57.node
    - $SWC_NAME-64.node
    - $SWC_NAME-67.node
  skip_cleanup: true
  on:
    tags: true
  
matrix:
  include:
    - os: windows
      env: SWC_NAME=win32-x64

    - os: linux
      env: SWC_NAME=linux-x64

    - os: osx
      osx_image: xcode9.2
      env: SWC_NAME=darwin-x64
