language: node_js
sudo: false


install:
  - node -v
  - which node
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - sh /tmp/rustup.sh --default-toolchain nightly -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - source "$HOME/.cargo/env"
  - yarn --ignore-scripts

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo
# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry


script:
  - neon build --release
  - mv native/index.node $BUILDNAME.node

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: $BUILDNAME
  skip_cleanup: true
  on:
    tags: true

matrix:
  include:
    - os: linux
      env: BUILDNAME=linux-6
      node_js: 6

    - os: osx
      osx_image: xcode9.2
      env: BUILDNAME=darwin-6      
      node_js: 6

    - os: linux
      env: BUILDNAME=linux-8
      node_js: 8

    - os: osx
      osx_image: xcode9.2
      env: BUILDNAME=darwin-8
      node_js: 8

    - os: linux
      env: BUILDNAME=linux-10
      node_js: 10

    - os: osx
      osx_image: xcode9.2
      env: BUILDNAME=darwin-10
      node_js: 10

