language: node_js
sudo: false


install:
  - node -v
  - which node
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - sh /tmp/rustup.sh --default-toolchain nightly -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - source "$HOME/.cargo/env"
  - npm install --ignore-scripts

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo
# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry


script:
  - neon build --release
  - mv native/index.node $BUILDNAME.node

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: $BUILDNAME.node
  skip_cleanup: true
  on:
    tags: true
  
matrix:
  include:
    - os: windows
      env: BUILDNAME=win32-x64-67
      node_js: 11

    - os: linux
      env: BUILDNAME=linux-x64-67
      node_js: 11

    - os: osx
      osx_image: xcode9.2
      env: BUILDNAME=darwin-x64-67
      node_js: 11

    - os: windows
      env: BUILDNAME=win32-x64-64
      node_js: 10

    - os: linux
      env: BUILDNAME=linux-x64-64
      node_js: 10

    - os: osx
      osx_image: xcode9.2
      env: BUILDNAME=darwin-x64-64
      node_js: 10

    - os: windows
      env: BUILDNAME=win32-x64-57
      node_js: 8

    - os: linux
      env: BUILDNAME=linux-x64-57
      node_js: 8

    - os: osx
      osx_image: xcode9.2
      env: BUILDNAME=darwin-x64-57
      node_js: 8

    - os: windows
      env: BUILDNAME=win32-x64-48
      node_js: 6

    - os: linux
      env: BUILDNAME=linux-x64-48
      node_js: 6

    - os: osx
      osx_image: xcode9.2
      env: BUILDNAME=darwin-x64-48
      node_js: 6

env:
  global:
    secure: XdeatOosEItjdAZXQWOJDPGI8Q65ytt8jsV28zJjdC4N7YaZZOrg/QJzWcteZzjFvAUeLDi2KffcKIoZUTAhIUc/wLOeyGny3Z3i6Z9QA7+R2XDpGo8ZPxL7sdRPgXHoLbKXm4RfNgjv/NXDvcZoAGPtqynt4fFQ6XzpZ9DLtU5jO5ukU1N4trcy8KuDOmhUVRMeT/9zDaItnm/AQwa7B63iJt3pi6bzcNdx5o5mepvLjTeeBrcSPt5NmTPKlsq77u1OYD2euykmPyJsd3ZH7BnG3RjXmFhV7IfpOr0v7xf13AYfyVZTKdL5xAcGrm0Sz1quLQfpiKraaJPNVtLbpjjP9iR8sqz82iQBMe6PLPvX4v9GhKVcIceIxIGA5HXedPAGY/XpxWCUXr1VmEHbstvR7nvOT74sE+KDJ4JVxIPmlZfjnjya3TQDyxEd24O3SRXz6jC6XvsqTy7JhCAcFH2oT90wiehB+P9aiSqct1P8fCv4qgaoNBLhlolUCf6o8vxqXBRFGwTngytERyqJpyFfasIQXcqQiB8VLGVAuu78xXIDkJSLcPZOtR3as1KENcfNdcOA0NLuppwyKxGZkAgmt9/Wz64OIUt9S8mKPmbbWWtvMJ3wwNAtlHx7118RDqwaiAZWsBTO2bDizZvUi7gOW2rmLF3qNjfZe/QLP+A=
