language: shell
sudo: false
osx_image: xcode11.3
services:
  - docker

branches:
  except:
    - master

install:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then rm -rf ~/.nvm ; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then git clone https://github.com/creationix/nvm.git ~/.nvm ; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then source ~/.nvm/nvm.sh ; fi
  - nvm version
  - nvm install 12.11.0
  - nvm install 11.6.0
  - nvm install 10.15.0
  - nvm install 8.15.0
  - which node
  - node --version
  - which npm
  # - npm --version

  # Install nightly rust
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then (curl https://sh.rustup.rs -sSf > /tmp/rustup.sh); fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then sh /tmp/rustup.sh --default-toolchain none -y; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then export PATH="$HOME/.cargo/bin:$PATH"; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then rustup toolchain install nightly; fi
  - ls -al ~/.rustup/toolchains

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  npm: true
  directories:
    - /home/travis/.cargo
# But don't cache the cargo registry
# before_cache:
#   - rm -rf /home/travis/.cargo/registry

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    # - $SWC_NAME-48.node
    - swc/$SWC_NAME-57.node
    - swc/$SWC_NAME-64.node
    - swc/$SWC_NAME-67.node
    - swc/$SWC_NAME-72.node
    - swc/$SWC_NAME-79.node
    - swc/$SWC_NAME-83.node
  skip_cleanup: true
  on:
    tags: true

matrix:
  include:

    - os: linux
      env:
        - SWC_NAME=linux-x64
        - NODE_ABI=83
      install:
        - ./scripts/ci/linux/start-docker.sh 14.2.0 83 14.x
      script:
        - travis_wait 30 docker exec target-83 sh ./scripts/ci/linux/build.sh 83

    - os: linux
      env:
        - SWC_NAME=linux-x64
        - NODE_ABI=79
      install:
        - ./scripts/ci/linux/start-docker.sh 13.3.0 79 13.x
      script:
        - travis_wait 30 docker exec target-79 sh ./scripts/ci/linux/build.sh 79

    - os: linux
      env:
        - SWC_NAME=linux-x64
        - NODE_ABI=72
      install:
        - ./scripts/ci/linux/start-docker.sh 12.12 72 12.x
      script:
        - travis_wait 30 docker exec target-72 sh ./scripts/ci/linux/build.sh 72

    - os: linux
      env:
        - SWC_NAME=linux-x64
        - NODE_ABI=64
      install:
        - ./scripts/ci/linux/start-docker.sh 10 64 10.x
      script:
        - travis_wait 30 docker exec target-64 sh ./scripts/ci/linux/build.sh 64

    - os: linux
      env:
        - SWC_NAME=linux-x64
        - NODE_ABI=57
      install:
        - ./scripts/ci/linux/start-docker.sh 8 57 8.x
      script:
        - travis_wait 30 docker exec target-57 sh ./scripts/ci/linux/build.sh 57

    # - os: linux
    #   env:
    #     - SWC_NAME=linux_musl-x64
    #     - NODE_ABI=83
    #   install:
    #     - ./scripts/ci/linux-musl/start-docker.sh 14.2.0 83 14
    #   script:
    #     - travis_wait 30 docker exec target-83 sh ./scripts/ci/linux-musl/build.sh 83

    # - os: linux
    #   env:
    #     - SWC_NAME=linux_musl-x64
    #     - NODE_ABI=79
    #   install:
    #     - ./scripts/ci/linux-musl/start-docker.sh 13.3.0 79 13
    #   script:
    #     - travis_wait 30 docker exec target-79 sh ./scripts/ci/linux-muslbuild.sh 79

    # - os: linux
    #   env:
    #     - SWC_NAME=linux_musl-x64
    #     - NODE_ABI=72
    #   install:
    #     - ./scripts/ci/linux-musl/start-docker.sh 12.12 72 12
    #   script:
    #     - travis_wait 30 docker exec target-72 sh ./scripts/ci/linux-muslbuild.sh 72

    # - os: linux
    #   env:
    #     - SWC_NAME=linux_musl-x64
    #     - NODE_ABI=64
    #   install:
    #     - ./scripts/ci/linux-musl/start-docker.sh 10 64 10
    #   script:
    #     - travis_wait 30 docker exec target-64 sh ./scripts/ci/linux-muslbuild.sh 64

    # - os: linux
    #   env:
    #     - SWC_NAME=linux_musl-x64
    #     - NODE_ABI=57
    #   install:
    #     - ./scripts/ci/linux-musl/start-docker.sh 8 57 8
    #   script:
    #     - travis_wait 30 docker exec target-57 sh ./scripts/ci/linux-muslbuild.sh 57
  
env:
  - CARGO_INCREMENTAL=0

notifications:
  slack:
    secure: Zof7PCQoe1TiksHUAU3hg3vwFBpxCvtJoGl0OlERHaKMtcMGF0SpcrYOtYHfjXXJx8RPW8nh/4A9sMp/ljoKP9K17IycwAoeGCqoE8fbqXtTf6IgIK+oKmMbFGLRcZLM0AtHv9xVP80WInNwQx+Si9TuuBL/yqBoOLYEc9o9I0euC7GM5DLD8/FXZeR28M+AraBCdFDUpTmEibWIc90pCHWPM7jWFVbCHrO/UqlwbficoNNRJiXYtVPw0dLGHI5feDP7lZMXRDggfwXaKa3IYPn0aEIrm8cM4RPd8LabuUmplZPu/+bBZnYAkB+JGPpC999eSnDTkI8GxPSJVVG3D5sbDGNB3XK/KKWT/Tn1GdJp0TJunYG5VGY7FiXs31J1xLqxVaBWEiEusC/TjUF2mK2oWSo9m5XVNGzN4XiMMzug5fmS0gbV283qnYY0nH5lDxeoBixeSqBkKPpMz4wbdV7kXkaTM5kPLQUw61+jw6AeKDDb6KcMt4xe4+/xwJg+Gbiey1ZcCwltcE79vqkoxwClJFvXA45UD96iylWiYx1pGQgBNs68v5mQgWF7M+M3UkeMHXsyJ+zKn6yxchumyvaQ9euW0AhY/GRkPZblfm6Lznk6qK2V/lOR6wsO5T+4TpIDAsIYgK+fFJioNbWujueXCfNvbVr2FntcwOH5Zmk=
