language: shell
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

install:
  # Install lastest nvm
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then curl -o /tmp/nvm.zip -L https://github.com/coreybutler/nvm-windows/releases/download/1.1.7/nvm-noinstall.zip ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cp ./scripts/ci/settings.txt C:\\ ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then mkdir C:\\nvm-root ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then unzip /tmp/nvm.zip -d C:\\nvm-root ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cp ./scripts/ci/settings.txt C:\\nvm-root\\ ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH="/c/nvm-root:/c/nodejs:$PATH" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export NVM_SYMLINK='C:\\nodejs' ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then nvm root C:\\nvm-root ; fi

  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then rm -rf ~/.nvm ; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then git clone https://github.com/creationix/nvm.git ~/.nvm ; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then source ~/.nvm/nvm.sh ; fi
  - nvm version
  - nvm install 12.11.0
  - nvm install 11.6.0
  - nvm install 10.15.0
  - nvm install 8.15.0
  # - nvm install 6.16.0
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then nvm on ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ls -al '/c/nodejs' ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ls -alL '/c/nodejs' ; fi
  - which node
  - node --version
  - which npm
  # - npm --version

  # Install nightly rust
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - sh /tmp/rustup.sh --default-toolchain none -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustup toolchain install nightly
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then rustup toolchain install nightly-x86_64-pc-windows-msvc ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then rustup default nightly-x86_64-pc-windows-msvc ; fi
  - ls -al ~/.rustup/toolchains

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  npm: true
  directories:
    - /home/travis/.cargo
# But don't cache the cargo registry
# before_cache:
#   - rm -rf /home/travis/.cargo/registry



script:
  - ${INDOCKER} travis_wait 30 bash ./scripts/ci/build.sh 12.11.0 72
  - ${INDOCKER} travis_wait 30 bash ./scripts/ci/build.sh 11.6.0 67
  - ${INDOCKER} travis_wait 30 bash ./scripts/ci/build.sh 10.15.0 64
  - ${INDOCKER} travis_wait 30 bash ./scripts/ci/build.sh 8.15.0 57
  # - bash ./scripts/ci/build.sh 6.16.0 48

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    # - $SWC_NAME-48.node
    - $SWC_NAME-57.node
    - $SWC_NAME-64.node
    - $SWC_NAME-67.node
    - $SWC_NAME-72.node
  skip_cleanup: true
  on:
    tags: true

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env: SWC_NAME=darwin-x64
      branches:
        except:
          - master

    # - os: windows
    #   env: SWC_NAME=win32-x64

    - os: linux
      env:
        - SWC_NAME=linux-x64
        - INDOCKER="docker exec target"
      services:
        - docker
      install:
        - ./scrints/ci/start-docker.sh
env:
  - CARGO_INCREMENTAL=0

notifications:
  slack:
    secure: Zof7PCQoe1TiksHUAU3hg3vwFBpxCvtJoGl0OlERHaKMtcMGF0SpcrYOtYHfjXXJx8RPW8nh/4A9sMp/ljoKP9K17IycwAoeGCqoE8fbqXtTf6IgIK+oKmMbFGLRcZLM0AtHv9xVP80WInNwQx+Si9TuuBL/yqBoOLYEc9o9I0euC7GM5DLD8/FXZeR28M+AraBCdFDUpTmEibWIc90pCHWPM7jWFVbCHrO/UqlwbficoNNRJiXYtVPw0dLGHI5feDP7lZMXRDggfwXaKa3IYPn0aEIrm8cM4RPd8LabuUmplZPu/+bBZnYAkB+JGPpC999eSnDTkI8GxPSJVVG3D5sbDGNB3XK/KKWT/Tn1GdJp0TJunYG5VGY7FiXs31J1xLqxVaBWEiEusC/TjUF2mK2oWSo9m5XVNGzN4XiMMzug5fmS0gbV283qnYY0nH5lDxeoBixeSqBkKPpMz4wbdV7kXkaTM5kPLQUw61+jw6AeKDDb6KcMt4xe4+/xwJg+Gbiey1ZcCwltcE79vqkoxwClJFvXA45UD96iylWiYx1pGQgBNs68v5mQgWF7M+M3UkeMHXsyJ+zKn6yxchumyvaQ9euW0AhY/GRkPZblfm6Lznk6qK2V/lOR6wsO5T+4TpIDAsIYgK+fFJioNbWujueXCfNvbVr2FntcwOH5Zmk=
