os: Visual Studio 2015

environment:
  RUST_BACKTRACE: 1
  matrix:
    - PLATFORM: x64

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe -y --default-toolchain none
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin;C:\\nvm-root;C:\nodejs
  - rustup toolchain install nightly-2019-01-09
  - rustup default nightly-2019-01-09
  - rustup show
  - rustc -V
  - cargo -V
  # Install nvm4w
  - curl -o C:\\nvm.zip -L https://github.com/coreybutler/nvm-windows/releases/download/1.1.7/nvm-noinstall.zip
  - cp ./scripts/ci/settings.txt C:\\
  - mkdir C:\\nvm-root
  - unzip C:\\nvm.zip -d C:\\nvm-root
  - cp ./scripts/ci/settings.txt C:\\nvm-root\\
  - set NVM_SYMLINK='C:\\nodejs'
  - nvm root C:\\nvm-root
  - nvm version
  - nvm install 11.6.0
  - nvm install 10.15.0
  - nvm install 8.15.0
  - nvm install 6.16.0

build: false

test_script:
  - bash ./scripts/ci/build.sh 11.6.0 67
  - bash ./scripts/ci/build.sh 10.15.0 64
  - bash ./scripts/ci/build.sh 8.15.0 57
  - bash ./scripts/ci/build.sh 6.16.0 48

cache:
  - target
  - C:\Users\appveyor\.cargo\registry