os: Visual Studio 2015

environment:
  RUST_BACKTRACE: 1
  matrix:
    - PLATFORM: x64
      NODEJS_VERSION: "11"
      RUST_TOOLCHAIN: nightly-x86_64-pc-windows-msvc
      RUSTFLAGS: "--cfg procmacro2_semver_exempt"
      BUILDNAME: win32-x64-67

    - PLATFORM: x64
      NODEJS_VERSION: "10"
      RUST_TOOLCHAIN: nightly-x86_64-pc-windows-msvc
      RUSTFLAGS: "--cfg procmacro2_semver_exempt"
      BUILDNAME: win32-x64-64

    - PLATFORM: x64
      NODEJS_VERSION: "8"
      RUST_TOOLCHAIN: nightly-x86_64-pc-windows-msvc
      RUSTFLAGS: "--cfg procmacro2_semver_exempt"
      BUILDNAME: win32-x64-57
      
    - PLATFORM: x64
      NODEJS_VERSION: "6"
      RUST_TOOLCHAIN: nightly-x86_64-pc-windows-msvc
      RUSTFLAGS: "--cfg procmacro2_semver_exempt"
      BUILDNAME: win32-x64-48
      
install:
  - ps: Install-Product node $env:NODEJS_VERSION $env:PLATFORM
  - npm config set msvs_version 2015
  - node -e "console.log(process.argv[0], process.arch, process.versions)"
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe -y --default-toolchain %RUST_TOOLCHAIN%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - set PATH=%APPDATA%\npm;%PATH%
  - rustup show
  - rustc -V
  - cargo -V
  - npm install -g neon-cli

build: false

test_script:
  - echo %RUSTFLAGS%
  - neon build --release

# skip_non_tags: true

cache:
  - target
  - C:\Users\appveyor\.cargo\registry

deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Prebuilt binaries'
  provider: GitHub
  auth_token:
    secure: <your encrypted token> # your encrypted token from GitHub
  artifact: index.node
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true  